### ISSUE TITLE
Internal server error - OpenpayServiceException(category=null, description=null, httpCode=405, errorCode=1000, requestId=null, riskData=null)

### ISSUE THREAD

**Issue by Nopalin** [open-pay/openpay-java#14]
Disculpen pedir ayuda por aquí, pero es que la persona que me esta atendiendo mediante soporte es nefasta, le proporciono código pero insiste en pedir capturas de pantalla, por lo que asumo que programador no es.

Ahora si, después del desahogo, estoy batallando para hacer el cargo. Genero el deviceSessionId con la libreria anti fraudes de javascript, posteriormente genero un tokenId igual con javascript enviandole la información de la tarjeta. Estos dos datos los envio al servidor donde usando la api de java intento realizar el cargo, lo estoy haciendo de ésta manera:
```
//la url esta hacia el sandbox, los otros dos datos igual son los de pruebas
OpenpayAPI api = new OpenpayAPI(openpayApiUrl, openpayPrivateId, openpayMerchantId);

Customer customer = new Customer();
customer.setName(params.getNombre());
customer.setLastName(StringUtils.EMPTY);
customer.setPhoneNumber(StringUtils.EMPTY);
customer.setEmail(params.getCorreo());

CreateCardChargeParams chargeParams = new CreateCardChargeParams()
	.cardId(params.getToken())
	.deviceSessionId(params.getDevice())
	.amount(precio.getTotal())
	.currency(Currency.MXN)
	.description("Compra realizada")
	.customer(customer);

Charge charge;
try {
	charge = api.charges().createCharge(chargeParams);
} catch(ServiceUnavailableException | OpenpayServiceException ex) {
	throw new RuntimeException(ex);
}
```

pero siempre me genera la siguiente excepción:
```
Caused by: mx.openpay.client.exceptions.OpenpayServiceException: [405] Internal server error
	at mx.openpay.client.core.JsonServiceClient.checkForErrors(JsonServiceClient.java:198)
	at mx.openpay.client.core.JsonServiceClient.postString(JsonServiceClient.java:173)
	at mx.openpay.client.core.JsonServiceClient.postObjectAsJson(JsonServiceClient.java:167)
	at mx.openpay.client.core.JsonServiceClient.post(JsonServiceClient.java:147)
	at mx.openpay.client.core.operations.ChargeOperations.createCharge(ChargeOperations.java:92)
```

Algo que se me este escapando? Aclaro que actualmente tenemos este cargo funcionando en un sistema con PHP sin problemas, estamos enviando la misma información que se envia aqui en java, solo que aqui siempre nos genera este error, les copio el logging que genera el http client de apache cuando realiza la llamada al api:
```
>> POST /v1/msjiloon6ehagjedgslk/charges HTTP/1.1
 >> User-Agent: openpay-java/1.7.0
 >> Accept: application/json
 >> Content-Type: application/json
 >> Authorization: Basic c2tfODlhZDc4ODBhZjM2NGUyMW.....
 >> Content-Length: 283
 >> Host: sandbox-dashboard.openpay.mx
 >> Connection: Keep-Alive
 >> Accept-Encoding: gzip,deflate
 >> "POST /v1/msjiloon6ehagjedgslk/charges HTTP/1.1[\r][\n]"
 >> "User-Agent: openpay-java/1.7.0[\r][\n]"
 >> "Accept: application/json[\r][\n]"
 >> "Content-Type: application/json[\r][\n]"
 >> "Authorization: Basic c2tfODlhZDc4ODBhZjM2NGUyMW.....[\r][\n]"
 >> "Content-Length: 283[\r][\n]"
 >> "Host: sandbox-dashboard.openpay.mx[\r][\n]"
 >> "Connection: Keep-Alive[\r][\n]"
 >> "Accept-Encoding: gzip,deflate[\r][\n]"
 >> "[\r][\n]"
 >> "{"device_session_id":"zI7hRumS3hHNrMlKWAz06PH0vjFk3rRg","amount":1450.000000000,"method":"card","description":"Compra realizada","currency":"MXN","source_id":"k15esro8sdjliin3y3sa","customer":{"name":"JOSE PEREZ","email":"jose.perez@gmail.com","last_name":"","phone_number":""}}"
 << "HTTP/1.1 405 [\r][\n]"
 << "Date: Thu, 20 Jul 2023 18:19:46 GMT[\r][\n]"
 << "Content-Length: 0[\r][\n]"
 << "Connection: keep-alive[\r][\n]"
 << "Set-Cookie: AWSALB=SxYHhArTEbY8cAnuqHMHp3uqG27Rc71+IyNPlGOQ6Gnw3UfffiSwBi02my1Tz+NH+TkNqbB+QQgGvZGkzwqeNpbH+9woN0A6f5pYQu/Wu0wehSOFQNOg3gbeWNk7; Expires=Thu, 27 Jul 2023 18:19:46 GMT; Path=/[\r][\n]"
 << "Set-Cookie: AWSALBCORS=SxYHhArTEbY8cAnuqHMHp3uqG27Rc71+IyNPlGOQ6Gnw3UfffiSwBi02my1Tz+NH+TkNqbB+QQgGvZGkzwqeNpbH+9woN0A6f5pYQu/Wu0wehSOFQNOg3gbeWNk7; Expires=Thu, 27 Jul 2023 18:19:46 GMT; Path=/; SameSite=None; Secure[\r][\n]"
 << "Cache-Control: no-cache, no-store, max-age=0, must-revalidate[\r][\n]"
 << "Pragma: no-cache[\r][\n]"
 << "Expires: 0[\r][\n]"
 << "Strict-Transport-Security: max-age=31536000 ; includeSubDomains[\r][\n]"
 << "X-XSS-Protection: 1; mode=block[\r][\n]"
 << "X-Frame-Options: DENY[\r][\n]"
 << "X-Content-Type-Options: nosniff[\r][\n]"
 << "Set-Cookie: JSESSIONID=92B41E191B7EA65CA0895002F8AA6AF9; Path=/; Secure; HttpOnly[\r][\n]"
 << "Allow: GET[\r][\n]"
 << "[\r][\n]"
 << HTTP/1.1 405 
 << Date: Thu, 20 Jul 2023 18:19:46 GMT
 << Content-Length: 0
 << Connection: keep-alive
 << Set-Cookie: AWSALB=SxYHhArTEbY8cAnuqHMHp3uqG27Rc71+IyNPlGOQ6Gnw3UfffiSwBi02my1Tz+NH+TkNqbB+QQgGvZGkzwqeNpbH+9woN0A6f5pYQu/Wu0wehSOFQNOg3gbeWNk7; Expires=Thu, 27 Jul 2023 18:19:46 GMT; Path=/
 << Set-Cookie: AWSALBCORS=SxYHhArTEbY8cAnuqHMHp3uqG27Rc71+IyNPlGOQ6Gnw3UfffiSwBi02my1Tz+NH+TkNqbB+QQgGvZGkzwqeNpbH+9woN0A6f5pYQu/Wu0wehSOFQNOg3gbeWNk7; Expires=Thu, 27 Jul 2023 18:19:46 GMT; Path=/; SameSite=None; Secure
 << Cache-Control: no-cache, no-store, max-age=0, must-revalidate
 << Pragma: no-cache
 << Expires: 0
 << Strict-Transport-Security: max-age=31536000 ; includeSubDomains
 << X-XSS-Protection: 1; mode=block
 << X-Frame-Options: DENY
 << X-Content-Type-Options: nosniff
 << Set-Cookie: JSESSIONID=92B41E191B7EA65CA0895002F8AA6AF9; Path=/; Secure; HttpOnly
 << Allow: GET
2023-07-20 13:19:46,836 ERROR [qtp1999415998-82]           mx.openpay.client.core.JsonServiceClient: Not a Json response. Code: 405, body:  
2023-07-20 13:19:53,179 DEBUG [qtp1999415998-82]    o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver: Using @ExceptionHandler server.controllers.support.ApiErrorsAdvice#exception(Exception, HttpServletResponse)
2023-07-20 13:19:53,179 ERROR [qtp1999415998-82]        a.server.controllers.support.ApiErrorsAdvice: ### exception
java.lang.RuntimeException: OpenpayServiceException(category=null, description=null, httpCode=405, errorCode=1000, requestId=null, riskData=null)
```

Gracias por su apoyo.

**Comment by Akumanokaze** [comment]
Hola, no uses la api de java, realmente no sirve. tuve ese problema tambien con la api, puedes usar "HttpClient" o "httpOk" de java , se comporta como hacer la petición desde navegador, para el segundo caso "httpOk " puedes hacer una petición desde postman y te dará el codigo java en automatico. cachar la respuesta en un String y parsearlo con Gson().fromJson(respuestahttp, respuesta.class);, eso te obliga a crear los objetos necesarios para enviar y recibir. pero funciona para recibir los errores y saber lo que te esta atorando.

**Comment by Nopalin** [comment]
Hola @Akumanokaze , la api funciona sin problemas, internamente utiliza HttpClient y la ventaja es que yo no me preocupo por armar los headers ni el contenido de la llamada Post. Mi problema era que movieron el servidor sandbox, ya no es sandbox-dashboard.openpay.mx ahora es sandbox-api.openpay.mx, aunque creo que deben deshabilitar el dominio anterior o poner un mensaje mas entendible en el nuevo, ya que ni si quiera los de soporte supieron decirme sobre este cambió a pesar de que les adjunte mas de 10 ejemplos con peticiones donde se veía claramente el servidor al que intentaba hacer la petición.

En fin, una tacha para los de soporte.
